import assert from 'node:assert/strict'
import test from 'node:test'
import { readFileSync } from 'node:fs'

const migration = readFileSync(
  new URL('../supabase/migrations/20260922000000_create_character_events.sql', import.meta.url),
  'utf8'
)

test('creates the shared character table with server timestamps and bounded selections', () => {
  assert.match(migration, /create table if not exists public\.character_events/i)
  assert.match(migration, /id bigint generated by default as identity primary key/i)
  assert.match(migration, /created_at timestamptz not null default now\(\)/i)
  assert.match(migration, /world_id text not null default 'shared-house'/i)
  assert.match(migration, /match_color smallint not null/i)
  assert.match(migration, /expression smallint not null/i)
  assert.match(migration, /flame_color smallint not null/i)
  assert.match(migration, /flame_shape smallint not null/i)
  assert.match(migration, /shoe smallint not null/i)
  assert.match(migration, /check \(match_color between 0 and 3\)/i)
  assert.match(migration, /check \(expression between 0 and 5\)/i)
  assert.match(migration, /check \(flame_color between 0 and 3\)/i)
  assert.match(migration, /check \(flame_shape between 0 and 5\)/i)
  assert.match(migration, /check \(shoe between 0 and 3\)/i)
})

test('secures recent shared character access and enables Realtime inserts', () => {
  assert.match(migration, /alter table public\.character_events enable row level security/i)
  assert.match(migration, /grant select, insert on public\.character_events to anon, authenticated/i)
  assert.match(migration, /for select[\s\S]*created_at >= now\(\) - interval '24 hours'/i)
  assert.match(migration, /for insert[\s\S]*with check[\s\S]*world_id = 'shared-house'/i)
  assert.match(migration, /alter publication supabase_realtime add table public\.character_events/i)
})
