-- Shared custom characters are ephemeral world events, not user profiles.
create table if not exists public.character_events (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  world_id text not null default 'shared-house',
  match_color smallint not null,
  expression smallint not null,
  flame_color smallint not null,
  flame_shape smallint not null,
  shoe smallint not null,
  constraint character_events_world_check check (world_id = 'shared-house'),
  constraint character_events_match_color_check check (match_color between 0 and 3),
  constraint character_events_expression_check check (expression between 0 and 5),
  constraint character_events_flame_color_check check (flame_color between 0 and 3),
  constraint character_events_flame_shape_check check (flame_shape between 0 and 5),
  constraint character_events_shoe_check check (shoe between 0 and 3)
);

create index if not exists character_events_created_at_id_idx
  on public.character_events (created_at, id);

alter table public.character_events enable row level security;

grant select, insert on public.character_events to anon, authenticated;
grant usage, select on sequence public.character_events_id_seq to anon, authenticated;
revoke insert (id, created_at) on public.character_events from anon, authenticated;

drop policy if exists "read recent shared characters" on public.character_events;
create policy "read recent shared characters"
  on public.character_events
  for select
  to anon, authenticated
  using (created_at >= now() - interval '24 hours');

drop policy if exists "create valid shared characters" on public.character_events;
create policy "create valid shared characters"
  on public.character_events
  for insert
  to anon, authenticated
  with check (
    world_id = 'shared-house'
    and created_at >= now() - interval '24 hours'
    and created_at <= now()
    and match_color between 0 and 3
    and expression between 0 and 5
    and flame_color between 0 and 3
    and flame_shape between 0 and 5
    and shoe between 0 and 3
  );

do $$
begin
  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'character_events'
  ) then
    alter publication supabase_realtime add table public.character_events;
  end if;
end
$$;
